name: 错误报告表格
description: 请使用最新的构建版本报告，你发现的问题很可能已经修复。  在进行错误报告之前，请确保没有类似的现有的报告。

body:
  - type: input
    id: version
    attributes:
      label: Mod 版本
      description: 例如1.20.1-3.0.0-rc1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 错误描述
      placeholder: "描述这个为什么是一个错误，是哪一方面的，以及其他可能需要的信息"
    validations:
      required: true
